package br.com.trabalhops.gui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import br.com.trabalhops.maquinavirtual.Instrucoes;
import br.com.trabalhops.maquinavirtual.Memoria;
import br.com.trabalhops.maquinavirtual.Registradores;
import java.io.IOException;
import java.util.Timer;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author junio
 */
public class Tela extends javax.swing.JFrame {

    public final Instrucoes instrucoes = new Instrucoes();
    public Registradores registradores;
    public Memoria memoria;
    public Dados dados;

    public Tela(Registradores registradores, Memoria memoria) {
        this.registradores = registradores;
        this.memoria = memoria;
        this.dados = new Dados();
        
        initComponents();
        console.setEditable(false);
    }

    public int lerTeclado() {
        String input = JOptionPane.showInputDialog(this, "Input");
        return Integer.parseInt(input);
    }

    public void escreveConsole(int valor) {
        console.append(Integer.toString(valor) + "\n");
    }

    public void preencheTabela(Memoria memoria) {
        String colunas[] = {"Endereço", "Valor"};
            
        DefaultTableModel model = new DefaultTableModel(dados.criaMatriz(memoria), colunas);
        tabelaMemoria.setModel(model);
    }

    public void preencheTabelaRegistradores(Registradores registradores) {
        String colunas[] = {"Registrador", "Valor"};

        DefaultTableModel model = new DefaultTableModel(dados.criaMatrizRegistradores(registradores), colunas);

        tabelaRegistradores.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modoOperacao = new javax.swing.ButtonGroup();
        jFileChooser1 = new javax.swing.JFileChooser();
        botaoExecutar = new javax.swing.JButton();
        tabelaMemoriaScroll = new javax.swing.JScrollPane();
        tabelaMemoria = new javax.swing.JTable();
        tabelaRegistradoresScroll = new javax.swing.JScrollPane();
        tabelaRegistradores = new javax.swing.JTable();
        modoStep = new javax.swing.JRadioButton();
        modoContinuo = new javax.swing.JRadioButton();
        modoIntervalo = new javax.swing.JRadioButton();
        consoleScroll = new javax.swing.JScrollPane();
        console = new javax.swing.JTextArea();
        resetButton = new javax.swing.JButton();
        toggleModoTabela = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        botaoExecutar.setBackground(new java.awt.Color(255, 255, 255));
        botaoExecutar.setForeground(new java.awt.Color(0, 0, 0));
        botaoExecutar.setText("Prox Instrução");
        botaoExecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExecutarActionPerformed(evt);
            }
        });

        tabelaMemoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Endereço", "Valor"
            }
        ));
        tabelaMemoriaScroll.setViewportView(tabelaMemoria);

        tabelaRegistradores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Registradores", "Valor"
            }
        ));
        tabelaRegistradoresScroll.setViewportView(tabelaRegistradores);

        modoStep.setBackground(new java.awt.Color(51, 204, 255));
        modoOperacao.add(modoStep);
        modoStep.setSelected(true);
        modoStep.setText("Manual");
        modoStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modoStepActionPerformed(evt);
            }
        });

        modoContinuo.setBackground(new java.awt.Color(51, 204, 255));
        modoOperacao.add(modoContinuo);
        modoContinuo.setText("Contínuo");
        modoContinuo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modoContinuoActionPerformed(evt);
            }
        });

        modoIntervalo.setBackground(new java.awt.Color(51, 204, 255));
        modoOperacao.add(modoIntervalo);
        modoIntervalo.setText("Depuração");
        modoIntervalo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modoIntervaloActionPerformed(evt);
            }
        });

        console.setColumns(20);
        console.setRows(5);
        consoleScroll.setViewportView(console);

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        toggleModoTabela.setText("Decimal");
        toggleModoTabela.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                toggleModoTabelaStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(toggleModoTabela)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resetButton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(modoStep)
                                        .addComponent(modoContinuo)
                                        .addComponent(modoIntervalo)
                                        .addComponent(botaoExecutar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(48, 48, 48)
                                    .addComponent(tabelaRegistradoresScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(consoleScroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45)
                        .addComponent(tabelaMemoriaScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(resetButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tabelaRegistradoresScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(modoStep)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(modoContinuo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(modoIntervalo)
                                .addGap(18, 18, 18)
                                .addComponent(botaoExecutar)))
                        .addGap(53, 53, 53)
                        .addComponent(consoleScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tabelaMemoriaScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(toggleModoTabela)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoExecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExecutarActionPerformed
        int mop = this.registradores.getMOP();

        switch (mop) {
            case 0 -> {
                instrucoes.getInstrucao(this);
                this.preencheTabelaRegistradores(registradores);
                this.preencheTabela(this.memoria);
            }
            case 1 -> {
                while (instrucoes.getInstrucao(this) != 0) {

                }
                this.preencheTabelaRegistradores(registradores);
                this.preencheTabela(this.memoria);
            }
            case 2 -> {                
                Timer timer = new Timer();
                timer.schedule(new TaskDepuracao(this), 0, 10);//wait 0 ms before doing the action and do it evry 1000ms (1second)
            }

            default -> {
                return;
            }
        }
    }//GEN-LAST:event_botaoExecutarActionPerformed

    private void modoStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modoStepActionPerformed
        this.registradores.setMOP(0);
        this.preencheTabelaRegistradores(registradores);
        botaoExecutar.setText("Prox Instrução");
    }//GEN-LAST:event_modoStepActionPerformed

    private void modoContinuoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modoContinuoActionPerformed
        this.registradores.setMOP(1);
        this.preencheTabelaRegistradores(registradores);
        botaoExecutar.setText("Executar");
    }//GEN-LAST:event_modoContinuoActionPerformed

    private void modoIntervaloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modoIntervaloActionPerformed
        this.registradores.setMOP(2);
        this.preencheTabelaRegistradores(registradores);
        botaoExecutar.setText("Executar");
    }//GEN-LAST:event_modoIntervaloActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        memoria.resetMemoria();
        registradores.resetRegistradores(memoria.getINICIO_INS_DADOS());
        try {
            memoria.carregaPrograma(memoria.programaCarregado);
        } catch (IOException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.preencheTabelaRegistradores(registradores);
        this.preencheTabela(this.memoria);
        console.setText("");
    }//GEN-LAST:event_resetButtonActionPerformed

    private void toggleModoTabelaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_toggleModoTabelaStateChanged
        dados.toggleDecimal();
        this.preencheTabela(this.memoria);
    }//GEN-LAST:event_toggleModoTabelaStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Tela().setVisible(true);
//            }
//        });

        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Tela().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoExecutar;
    private javax.swing.JTextArea console;
    private javax.swing.JScrollPane consoleScroll;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JRadioButton modoContinuo;
    private javax.swing.JRadioButton modoIntervalo;
    private javax.swing.ButtonGroup modoOperacao;
    private javax.swing.JRadioButton modoStep;
    private javax.swing.JButton resetButton;
    private javax.swing.JTable tabelaMemoria;
    private javax.swing.JScrollPane tabelaMemoriaScroll;
    private javax.swing.JTable tabelaRegistradores;
    private javax.swing.JScrollPane tabelaRegistradoresScroll;
    private javax.swing.JToggleButton toggleModoTabela;
    // End of variables declaration//GEN-END:variables
}
